FROM rockylinux:9
RUN dnf install -y --allowerasing \
        --setopt=install_weak_deps=False \
        nss curl ca-certificates which tar cronie procps-ng libnotify \
        expat popt xorg-x11-server-Xvfb net-tools \
        dbus-libs atk at-spi2-atk cups-libs gtk3 pango cairo \
        libXcomposite libXdamage libXfixes libxkbcommon \
        alsa-lib at-spi2-core \
    && dnf clean all \
    && rm -rf /var/cache/dnf
